version: "3.9"

services:
  app:
    build: .
    image: unpaksiamida:latest
    ports:
      - "3000:3000"

    read_only: true
    tmpfs:
      - /tmp

    security_opt:
      - no-new-privileges:true
      - seccomp:./security/seccomp.json
      - apparmor:golang-fiber

    cap_drop:
      - ALL

    restart: unless-stopped

    environment:
      DB_SIMONEV: ${DB_SIMONEV}
      DB_SIMAK: ${DB_SIMAK}
      DB_SIMPEG: ${DB_SIMPEG}