// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fakultasunit/{uuid}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FakultasUnit"
                ],
                "summary": "Get FakultasUnit by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "FakultasUnit UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.FakultasUnit"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/domain.Error"
                        }
                    }
                }
            }
        },
        "/fakultasunits": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FakultasUnit"
                ],
                "summary": "Get All FakultasUnit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "paging | all | ndjson | sse",
                        "name": "mode",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PagedFakultasUnits"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.ErrorType"
                }
            }
        },
        "domain.ErrorType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "ErrorFailure",
                "Validation",
                "Problem",
                "NotFound",
                "Conflict"
            ]
        },
        "domain.FakultasUnit": {
            "type": "object",
            "properties": {
                "fakultas": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jenjang": {
                    "type": "string"
                },
                "kodeJenjang": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "domain.PagedFakultasUnits": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.FakultasUnit"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "UnpakSiamidaV2 API",
	Description:      "All Module Siamida",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
