name: Auto Release Docker

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # =========================
      # Checkout
      # =========================
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # =========================
      # Setup Go + Swagger
      # =========================
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.4

      # =========================
      # Run Tests
      # =========================
      - name: Run Unit Tests
        run: |
          go test ./... \
            -covermode=atomic \
            -coverprofile=coverage.out

      # =========================
      # Generate Coverage HTML
      # =========================
      - name: Generate Coverage Report
        run: |
          mkdir -p coverage

          go tool cover \
            -html=coverage.out \
            -o coverage/index.html

          go tool cover \
            -func=coverage.out \
            > coverage/summary.txt

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger
        run: swag init

      # =========================
      # Doc
      # =========================
      - name: Prepare GitHub Pages
        run: |
          rm -rf public
          mkdir -p public
          mkdir -p public/swagger
          mkdir -p public/coverage

          # =========================
          # Coverage
          # =========================
          cp coverage/index.html public/coverage/index.html
          cp coverage/summary.txt public/coverage/summary.txt

          # =========================
          # Swagger JSON
          # =========================
          cp docs/swagger.json public/swagger/swagger.json

          # =========================
          # Swagger UI
          # =========================
          cat <<EOF > public/swagger/index.html
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8" />
            <title>Swagger API</title>

            <link rel="stylesheet"
              href="https://unpkg.com/swagger-ui-dist/swagger-ui.css" />
          </head>
          <body>
            <div id="swagger-ui"></div>

            <script src="https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js"></script>

            <script>
              SwaggerUIBundle({
                url: './swagger.json',
                dom_id: '#swagger-ui',
                deepLinking: true
              });
            </script>
          </body>
          </html>
          EOF

          # =========================
          # Home Page
          # =========================
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Documentation Portal</title>

            <style>
              body{
                font-family:Arial;
                max-width:900px;
                margin:auto;
                padding:40px;
              }

              a{
                display:block;
                margin:10px 0;
                font-size:18px;
              }
            </style>
          </head>
          <body>

            <h1>Unpak Simonev V2</h1>

            <a href="./swagger/">📘 Swagger Documentation</a>
            <a href="./coverage/">🧪 Test Coverage</a>

          </body>
          </html>
          EOF

      # =========================
      # Deploy ke GitHub Pages
      # =========================
      - name: Deploy Swagger to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # =========================
      # Versioning
      # =========================
      - name: Get latest tag
        id: tag
        run: |
          latest=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$latest" ]; then
            latest="v1.0.0"
          fi
          echo "LATEST=$latest" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: version
        run: |
          tag=${{ steps.tag.outputs.LATEST }}
          version=${tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new="v$major.$minor.$patch"
          echo "NEW_TAG=$new" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.version.outputs.NEW_TAG }}
          git push origin ${{ steps.version.outputs.NEW_TAG }}

      # =========================
      # Docker
      # =========================
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            adamilkom00/unpaksimonevv2_be:${{ steps.version.outputs.NEW_TAG }}
            adamilkom00/unpaksimonevv2_be:latest